// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riypzobebledoxczvzen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpeXB6b2JlYmxlZG94Y3p2emVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODg5OTQsImV4cCI6MjA2NjI2NDk5NH0.PZeWRTsUOihPLXzBML3fwVF_6gFz4CzzlGsrrLPl7XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);